//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanlineaTest.Contacts {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BanlineaTest.Contacts.NetResources", typeof(NetResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/DrTJahed.
        /// </summary>
        public static string FacebookProfileUrl {
            get {
                return ResourceManager.GetString("FacebookProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string GetCountriesUrl {
            get {
                return ResourceManager.GetString("GetCountriesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/drtj2066/?hl=en.
        /// </summary>
        public static string InstagramProfileUrl {
            get {
                return ResourceManager.GetString("InstagramProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://co.linkedin.com/in/drtj2066.
        /// </summary>
        public static string LinkedInProfileUrl {
            get {
                return ResourceManager.GetString("LinkedInProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactRegister.
        /// </summary>
        public static string RegisterContactUrl {
            get {
                return ResourceManager.GetString("RegisterContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://contactmanager.banlinea.com/api/.
        /// </summary>
        public static string ServiceBaseUrl {
            get {
                return ResourceManager.GetString("ServiceBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://stackoverflow.com/users/451383/dr-tj?tab=profile.
        /// </summary>
        public static string StackoverflowProfileUrl {
            get {
                return ResourceManager.GetString("StackoverflowProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/drtj2066.
        /// </summary>
        public static string TwitterProfileUrl {
            get {
                return ResourceManager.GetString("TwitterProfileUrl", resourceCulture);
            }
        }
    }
}
