//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanlineaTest.Contacts {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BanlineaTest.Contacts.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohammad Taghi Jahed.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contacto.
        /// </summary>
        public static string AddContactPageTitle {
            get {
                return ResourceManager.GetString("AddContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la empresa.
        /// </summary>
        public static string CompanyNamePlaceholder {
            get {
                return ResourceManager.GetString("CompanyNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe digitar un correo.
        /// </summary>
        public static string DebeDigitarUnCorreo {
            get {
                return ResourceManager.GetString("DebeDigitarUnCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe digitar un numero de celular.
        /// </summary>
        public static string DebeDigitarUnNumeroDeCelular {
            get {
                return ResourceManager.GetString("DebeDigitarUnNumeroDeCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo no es valido.
        /// </summary>
        public static string ElCorreoNoEsValido {
            get {
                return ResourceManager.GetString("ElCorreoNoEsValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El numero de celular no es valido.
        /// </summary>
        public static string ElNumeroDeCelularNoEsValido {
            get {
                return ResourceManager.GetString("ElNumeroDeCelularNoEsValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electronico.
        /// </summary>
        public static string EmailAddressPlaceholder {
            get {
                return ResourceManager.GetString("EmailAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banlinea Contacts.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar un Email.
        /// </summary>
        public static string MoreEmailsButtonText {
            get {
                return ResourceManager.GetString("MoreEmailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar un Numero.
        /// </summary>
        public static string MorePhoneNumbersButtonText {
            get {
                return ResourceManager.GetString("MorePhoneNumbersButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay camera disponible..
        /// </summary>
        public static string NoCameraAvailable {
            get {
                return ResourceManager.GetString("NoCameraAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningun contacto registrado.
        /// </summary>
        public static string NoHayRegistro {
            get {
                return ResourceManager.GetString("NoHayRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de teléfono.
        /// </summary>
        public static string PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taghi.Jahed@yahoo.com.
        /// </summary>
        public static string ProgrammerEmail {
            get {
                return ResourceManager.GetString("ProgrammerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohammad Taghi Jahed.
        /// </summary>
        public static string ProgrammerName {
            get {
                return ResourceManager.GetString("ProgrammerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3044337163.
        /// </summary>
        public static string ProgrammerPhone {
            get {
                return ResourceManager.GetString("ProgrammerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el país.
        /// </summary>
        public static string SelectCountryActionSheetTitle {
            get {
                return ResourceManager.GetString("SelectCountryActionSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los campos son requeridos..
        /// </summary>
        public static string TodosLosCamposSonRequeridos {
            get {
                return ResourceManager.GetString("TodosLosCamposSonRequeridos", resourceCulture);
            }
        }
    }
}
